language: node_js
node_js:
  - "0.10"
  - "0.8"
before_install: 
  - sudo add-apt-repository -y ppa:duh/golang
  - sudo apt-get update
  - sudo apt-get install -y golang
  - sudo git clone https://github.com/coreos/etcd.git /opt/etcd
  - cd /opt/etcd && sudo ./build
  - sudo /opt/etcd/etcd &
  - cd $TRAVIS_BUILD_DIR